#pragma once

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_MAX_SPEED 40
#define MOUSEKEY_TIME_TO_MAX 64
#define MOUSEKEY_FRICTION 6
#define MOUSEKEY_WHEEL_MAX_SPEED 16
#define MOUSEKEY_WHEEL_TIME_TO_MAX 64

#define PERMISSIVE_HOLD
