#pragma once

#define MK_KINETIC_SPEED

#define MOUSEKEY_MOVE_DELTA 175
#define MOUSEKEY_INITIAL_SPEED 300
#define MOUSEKEY_BASE_SPEED 1200

#define MOUSEKEY_INITIAL_MOVEMENTS 4
#define MOUSEKEY_BASE_MOVEMENTS 16
#define MOUSEKEY_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_DECELERATED_MOVEMENTS 4

#define NO_ACTION_ONESHOT
#define NO_USB_STARTUP_CHECK
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#undef RAW_IN_CAPACITY
#undef RAW_OUT_CAPACITY
#define RAW_IN_CAPACITY 2
#define RAW_OUT_CAPACITY 2

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_DEFAULT_HUE 154
#define RGB_MATRIX_DEFAULT_SAT 216

#define RGB_MATRIX_DISABLE_KEYCODES

#undef RGB_MATRIX_STARTUP_MODE
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#define ENABLE_RGB_MATRIX_BREATHING
#endif // RGB_MATRIX_ENABLE
