#pragma once

#define MK_KINETIC_SPEED

#define MOUSEKEY_MOVE_DELTA 160
#define MOUSEKEY_INITIAL_SPEED 350
#define MOUSEKEY_BASE_SPEED 1200

#define MOUSEKEY_INITIAL_MOVEMENTS 8
#define MOUSEKEY_BASE_MOVEMENTS 16
#define MOUSEKEY_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_DECELERATED_MOVEMENTS 4

#define NO_ACTION_ONESHOT
#define NO_USB_STARTUP_CHECK

#define RGB_MATRIX_DISABLE_KEYCODES

#define RGB_MATRIX_DEFAULT_HUE 154
#define RGB_MATRIX_DEFAULT_SAT 216

#undef RGB_MATRIX_STARTUP_MODE
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#define ENABLE_RGB_MATRIX_BREATHING
