#pragma once

// thanks ppy
#define MK_VARIANT MK_TYPE_KINETIC

#define MK_KINETIC_MOUSE_MAXS 32
#define MK_KINETIC_MOUSE_ACCN 40
#define MK_KINETIC_MOUSE_FRIC 18
#define MK_KINETIC_MOUSE_DRAG 18

#define MK_KINETIC_WHEEL_FRIC 16
#define MK_KINETIC_WHEEL_DRAG 16
#define MK_KINETIC_WHEEL_MAXS 2
#define MK_KINETIC_WHEEL_ACCN 16

#define NO_ACTION_ONESHOT
#define NO_USB_STARTUP_CHECK
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#undef RAW_IN_CAPACITY
#undef RAW_OUT_CAPACITY
#define RAW_IN_CAPACITY 2
#define RAW_OUT_CAPACITY 2

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_DEFAULT_HUE 154
#define RGB_MATRIX_DEFAULT_SAT 216

#define RGB_MATRIX_DISABLE_KEYCODES

#undef RGB_MATRIX_STARTUP_MODE
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#define ENABLE_RGB_MATRIX_BREATHING
#endif // RGB_MATRIX_ENABLE
