SRC += protocol.c

MOUSEKEY_ENABLE = yes

EEPROM_DRIVER = transient

BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

RGB_MATRIX_ENABLE = no
RAW_ENABLE = yes
